plugins:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 200

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/HashSyntax:
  EnforcedStyle: ruby19

# Metrics exceptions for complex tool methods
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/ferrum_mcp/tools/**/*'
    - 'lib/ferrum_mcp/server.rb'

Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/ferrum_mcp/tools/**/*'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/ferrum_mcp/tools/**/*'

# RSpec configuration
RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/DescribeClass:
  Enabled: false
